
learn_system:
  type: LEMURS
  policy: FS
  num_agents: 4
  depth: 3
teacher: 
  max_difficulty: 50
  difficulty_grouper: steps
  difficulty_resolution: 10
  type: online
  learning_rate: 0.001
  reward: l2loss
general:
  epochs: 10000
  train_size: 20000
  val_size: 2000
  seed_data: 42
  seed_train: 50
  early_stopping: false