
learn_system:
  type: LEMURS
  policy: FS
  num_agents: 4
  depth: 3
teacher: 
  max_difficulty: 50
  difficulty_grouper: steps
  difficulty_resolution: 10
  type: babysteps
  interval_policy: fixed
  interval_parameter: 200
  increment_policy: fixed
  increment_parameter: 1
  old_task_quota: 0.2
general:
  epochs: 1000
  train_size: 20000
  val_size: 2000
  seed_data: 42
  seed_train: 50
  early_stopping: false